---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gerai270/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan storage:link